### ISSUE TITLE
unsupported on jekyll 1.5.1

### ISSUE THREAD

**Issue by VRMink** [kronik3r/daktilo#2]
Which version of jekyll is this designed for?
Do I need any additional packages to generate the css from the sass file, or will the right version of jekyll handle that?

**Comment by kronik3r** [comment]
@VRMink I designed it for the latest version (which is 2.5.3), aside that you will need no dependency, actually that was my intent from the get going, that's why I implemented the categories using only basic concepts without the need of any additional plugin. Yeah, just upgrade to the latest version and everything will be working great!
