### ISSUE TITLE
Can't change colo(u)r of post content

### ISSUE THREAD

**Issue by ghost** [kronik3r/daktilo#5]
I'm _really_ new to Jekyll so I may be approaching this wrong, but a least help me here.

I loved this theme but just wanted to have a dark background. I changed a few colours for the background, title, etc. in `_sass/_default.scss` and `css/main.scss`. However, I am hard-pressed to change the colour of a post's text to white! 

I had a look, and saw that posts adapt the post layout. OK, I say. Here it is:

``` html

---
layout: default

---
{% include post/title.html %}

<div class="content">
    {{ content }}
</div>

{% include post/about.html %}
```

Oh! Well, that should be simple enough. I added this to `main.scss`:

``` css
.content
{
    color: white;
}
```

No - that doesn't work. I try doing that in `_default.scss` too. No effect. I try doing this to the `<div>` part:

``` html
<div class="content">
    <p style="color:white;">
    {{ content }}
    </p>
</div>
```

And still no effect.

How do I do this?

**Comment by kronik3r** [comment]
Hello @eshansingh :),

The issue here is that in the `_default.scss` file at the beginning there's a base styling for all `p` tags, this one take precedence over all other styling, that's why when you style `.content` it don't take affect. I fixed that to avoid all future confusion, pull the latest code and you're styling will work just fine :+1: .

Also I highly recommend you read this great [resource on css rules precedence](https://css-tricks.com/specifics-on-css-specificity/).

PS: Don't forget that we are people too just like you :) and we are doing this for fun. Try to be more polite next time.

**Comment by ghost** [comment]
Yes, you're right. Really sorry. I sometimes don't realize when I'm being rude.

**Comment by kronik3r** [comment]
No problem man :D happy coding and share with us what you've built.
